### ISSUE TITLE
Ability to specify attributes for each link

### ISSUE THREAD

**Issue by 4n70w4** [coffee2code/linkify-text#9]
Example: alt, title, class, id and etc

**Comment by coffee2code** [comment]
This is already possible via the `c2c_linkify_text_link_attrs` filter, which is documented in the "Hooks" section of readme.txt.

**Comment by 4n70w4** [comment]
@coffee2code  `c2c_linkify_text_link_attrs` filter too complicated, I (typically user) do not understand how this works without additional study of the WordPress documentation.

My issue about a request to manage this through the interface.

First of all, I would set title-attribute to all links to my blog entries from its post title.
Can this case be make to a separate functional that is enabled via the checkbox?

**Comment by 4n70w4** [comment]
May be add support second format if need add attributes:

`google => <a href="https://google.com" attr1="val1" attr2="val2" />`

@coffee2code how do you look at it? Beautiful and elegant solution.
